import localFont from "next/font/local";
import "./globals.css";
import { HeaderSimple } from './header'; // Import the HeaderSimple component
import Head from 'next/head'; // Import the Head component to modify <head> section

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://use.typekit.net/ayk0qzf.css" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <div className='background-graphics'>
        <img src='./Asset 1.svg' className='asset1' />
        <img src='./Asset 2.svg' className='asset2' />
        <img src='./Asset 3.svg' className='asset3' />
        <img src='./Asset 4.svg' className='asset4' />
      </div>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Only light mode is applied */}
        <HeaderSimple />
        <main>{children}</main> {/* Main content will be passed as children */}
      </body>
    </html>
  );
}
